"""schema inicial

Revision ID: a0b3c4259cb2
Revises: 
Create Date: 2026-09-28 08:54:17.242895

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a0b3c4259cb2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alergenos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('icone', sa.String(), nullable=True),
    sa.Column('descricao', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('empresas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('slug', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome'),
    sa.UniqueConstraint('slug')
    )
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'tipo', 'nome', name='uq_categoria_empresa_tipo_nome')
    )
    op.create_index(op.f('ix_categorias_empresa_id'), 'categorias', ['empresa_id'], unique=False)
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('senha_hash', sa.String(), nullable=False),
    sa.Column('senha_provisoria', sa.Boolean(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('papel', sa.String(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('acessos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_acessos_criado_em'), 'acessos', ['criado_em'], unique=False)
    op.create_index(op.f('ix_acessos_empresa_id'), 'acessos', ['empresa_id'], unique=False)
    op.create_index(op.f('ix_acessos_usuario_id'), 'acessos', ['usuario_id'], unique=False)
    op.create_table('insumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('unidade_medida', sa.String(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nome', name='uq_insumo_empresa_nome')
    )
    op.create_index(op.f('ix_insumos_empresa_id'), 'insumos', ['empresa_id'], unique=False)
    op.create_table('log_auditoria',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=False),
    sa.Column('acao', sa.String(), nullable=False),
    sa.Column('entidade', sa.String(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_log_auditoria_empresa_id'), 'log_auditoria', ['empresa_id'], unique=False)
    op.create_table('receitas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('empresa_id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('rendimento_quantidade', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('rendimento_unidade', sa.String(), nullable=False),
    sa.Column('foto_url', sa.String(), nullable=True),
    sa.Column('observacoes', sa.String(), nullable=True),
    sa.Column('dificuldade', sa.String(), nullable=True),
    sa.Column('verificada', sa.Boolean(), nullable=False),
    sa.Column('verificada_em', sa.DateTime(), nullable=True),
    sa.Column('validade_congelado_dias', sa.Integer(), nullable=True),
    sa.Column('validade_refrigerado_dias', sa.Integer(), nullable=True),
    sa.Column('validade_ambiente_dias', sa.Integer(), nullable=True),
    sa.Column('ativa', sa.Boolean(), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['empresa_id'], ['empresas.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('empresa_id', 'nome', name='uq_receita_empresa_nome')
    )
    op.create_index(op.f('ix_receitas_empresa_id'), 'receitas', ['empresa_id'], unique=False)
    op.create_table('passos_preparo',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('ordem', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.String(), nullable=False),
    sa.Column('tempo_min', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_passos_preparo_receita_id'), 'passos_preparo', ['receita_id'], unique=False)
    op.create_table('receita_alergenos',
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('alergeno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['alergeno_id'], ['alergenos.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('receita_id', 'alergeno_id')
    )
    op.create_table('receita_insumos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('receita_id', sa.Integer(), nullable=False),
    sa.Column('insumo_id', sa.Integer(), nullable=True),
    sa.Column('sub_receita_id', sa.Integer(), nullable=True),
    sa.Column('quantidade', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('unidade_sub_receita', sa.String(), nullable=True),
    sa.Column('observacao', sa.String(), nullable=True),
    sa.CheckConstraint('(insumo_id IS NOT NULL) != (sub_receita_id IS NOT NULL)', name='ck_receita_insumo_um_tipo'),
    sa.ForeignKeyConstraint(['insumo_id'], ['insumos.id'], ),
    sa.ForeignKeyConstraint(['receita_id'], ['receitas.id'], ),
    sa.ForeignKeyConstraint(['sub_receita_id'], ['receitas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receita_insumos_receita_id'), 'receita_insumos', ['receita_id'], unique=False)
    op.create_index(op.f('ix_receita_insumos_sub_receita_id'), 'receita_insumos', ['sub_receita_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receita_insumos_sub_receita_id'), table_name='receita_insumos')
    op.drop_index(op.f('ix_receita_insumos_receita_id'), table_name='receita_insumos')
    op.drop_table('receita_insumos')
    op.drop_table('receita_alergenos')
    op.drop_index(op.f('ix_passos_preparo_receita_id'), table_name='passos_preparo')
    op.drop_table('passos_preparo')
    op.drop_index(op.f('ix_receitas_empresa_id'), table_name='receitas')
    op.drop_table('receitas')
    op.drop_index(op.f('ix_log_auditoria_empresa_id'), table_name='log_auditoria')
    op.drop_table('log_auditoria')
    op.drop_index(op.f('ix_insumos_empresa_id'), table_name='insumos')
    op.drop_table('insumos')
    op.drop_index(op.f('ix_acessos_usuario_id'), table_name='acessos')
    op.drop_index(op.f('ix_acessos_empresa_id'), table_name='acessos')
    op.drop_index(op.f('ix_acessos_criado_em'), table_name='acessos')
    op.drop_table('acessos')
    op.drop_table('usuarios')
    op.drop_index(op.f('ix_categorias_empresa_id'), table_name='categorias')
    op.drop_table('categorias')
    op.drop_table('empresas')
    op.drop_table('alergenos')
    # ### end Alembic commands ###
